### ISSUE TITLE
Provide support for recurring tasks

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#10]
This idea is more of an extra feature and hence can be considered later on when other major features have been implemented. Sometimes there is a need for setting a recurring tasks. 

One way of implementing this idea would be adding an option list next to the due date field. In the option list, you can list repeat every day, week, month and year. Once the due date is crossed, then the task should update the due date according to the repeat option set by the user.

**Comment by iBelieve** [comment]
I was thinking a little about this a while back, but couldn't think of a way to handle completing tasks that reoccur. However, I just thought of a way:

When a task gets completed that has a repetition set, the task will be duplicated for the next due date. This way, the user will never see more than the next task ahead, and I won't have to worry that changing the repetition settings will have to update all instances of the task. I'd rather not just update the due date but instead duplicate the task so the completed task shows in the statistics view and completed tasks view so the user can un-complete it if needed.

Does this sound good to you? I don't want to update the due date when it gets crossed, because then the user wouldn't see that the task is overdue. Instead, I'd rather wait until it gets completed to update it.

**Comment by krnekhelesh** [comment]
Yup that sounds good to me.
