### ISSUE TITLE
Sidebar inconsistency

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#19]
**Sidebar placement**
In the homepage, the sidebar is on the left showing the projects. However while creating a new task, the sidebar is now shown in the right with common task options like checklist, due date etc. Why?

**Comment by iBelieve** [comment]
After trying putting the sidebar on the left, I just didn't like it. It made more sense to me to put it on the right.

I ended up asking on [ux.stackexchange](http://ux.stackexchange.com/q/43996/34794), and was told that since the two pages are different things, the sidebar placement doesn't need to be consistent.

So I guess I'm just going to leave the task options sidebar on the right for now.

**Comment by krnekhelesh** [comment]
okay first I did not know that ux.stackchange even existed. That's pretty cool. And secondly, the reasoning that they provide in that answer is quite sound. Good decision to keep it as it is.
