### ISSUE TITLE
Disabling Trello integration does not remove trello tasks

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#44]
After painstakingly entering the so long token id on the phone, I got the trello boards but noticed some bugs,
1. I noticed that the app froze while the boards were being downloaded. 
2. One of my boards was not displayed properly. For instance the checklist percentage was overlapping the task title in the list view. (See screenshot)
3. After disabling trello integration, it removed the projects (since I did not see them there) but the tasks still remained in the overview and search page.

See screenshot at http://imgur.com/Yk1nFng

**Comment by iBelieve** [comment]
1. I don't know why this happens, it never happens on the desktop. As a work around, I've made the app switch to the projects tab so the user can see Trello is being loaded.
2. I fixed the percentage. The reason there is no checkboxes for some projects is because that project doesn't have a To Do/Done list, so Ubuntu Tasks doesn't know how to handle the concept of completing a task.
3. Fixed that.
