### ISSUE TITLE
App not working when I click the icon

### ISSUE THREAD

**Issue by amedee** [sonrisesoftware/tasks-app#56]
I just purchased this app through the Ubuntu store, the icon is in the task bar on the left, but nothing actually happens when I click the icon.

Ubuntu 14.04 LTS.

**Comment by SpeedyHenkie** [comment]
Same here! I also purchased the app, then installed it en re-installed it again. Icon is in the taskbar, but after clicking the icon the program does not start, in fact in does not do anything at all!

Working with Ubuntu 14.04 LTS

**Comment by iBelieve** [comment]
Hi guys, I'm really sorry you're having problems. This is caused by a bug made by the reviewer at Canonical, and was not caused by me. I've tried to get them to fix it, but apps for the Software Center aren't being reviewed much anymore.

Here is how you can fix it yourselves:

Open a Terminal and type: `sudo nano /opt/ubuntu-tasks/launcher.sh`

Then you should see a line that says:

```
/usr/bin/qmlscene -qt=$(qtchooser -list-versions | grep linux) run /opt/ubuntu-tasks/ubuntu-tasks.qml
```

Replace the part with the dollar symbol and in parentheses to match this line:

```
/usr/bin/qmlscene -qt=qt5 run /opt/ubuntu-tasks/ubuntu-tasks.qml
```

Then type Ctrl+O and then Ctrl+X to save your changes and exit the program.

**Comment by SpeedyHenkie** [comment]
Thanks for your reply. Now it works! Thanks

-----Oorspronkelijke bericht-----
Van: Michael Spencer notifications@github.com
Reply-to: sonrisesoftware/tasks-app <reply
+i-38881123-1f4df71b20d2a13eea13533d5ba3b9b90dbd582e-8302269@reply.github.com>
Aan: sonrisesoftware/tasks-app tasks-app@noreply.github.com
Cc: SpeedyHenkie jhendrik@worldonline.nl
Onderwerp: Re: [tasks-app] App not working when I click the icon (#56)
Datum: Tue, 29 Jul 2014 11:48:09 -0700

Hi guys, I'm really sorry you're having problems. This is caused by a
bug made by the reviewer at Canonical, and was not caused by me. I've
tried to get them to fix it, but apps for the Software Center aren't
being reviewed much anymore.

Here is how you can fix it yourselves:

Open a Terminal and type: sudo nano /opt/ubuntu-tasks/launcher.sh

Then you should see a line that says:

/usr/bin/qmlscene -qt=$(qtchooser -list-versions | grep linux) run /opt/ubuntu-tasks/ubuntu-tasks.qml

Replace the part with the dollar symbol and in parentheses to match this
line:

/usr/bin/qmlscene -qt=qt5 run /opt/ubuntu-tasks/ubuntu-tasks.qml

Then type Ctrl+O and then Ctrl+X to save your changes and exit the
program.

**Comment by amedee** [comment]
> Hi guys, I'm really sorry you're having problems. This is caused by a bug
> made by the reviewer at Canonical, and was not caused by me. I've tried to
> get them to fix it, but apps for the Software Center aren't being reviewed
> much anymore.
> 
> Here is how you can fix it yourselves:
> 
> Open a Terminal and type: `sudo nano /opt/ubuntu-tasks/launcher.sh`
> 
> Then you should see a line that says:
> 
> ```
> /usr/bin/qmlscene -qt=$(qtchooser -list-versions | grep linux) run
> ```
> 
> /opt/ubuntu-tasks/ubuntu-tasks.qml
> 
> Replace the part with the dollar symbol and in parentheses to match this
> line:
> 
> ```
> /usr/bin/qmlscene -qt=qt5 run /opt/ubuntu-tasks/ubuntu-tasks.qml
> ```
> 
> Then type Ctrl+O and then Ctrl+X to save your changes and exit the
> program.

Ok, you have a confusing way of putting it, first I thought you meant
(replace the part in parenthesis to match this):

```
/usr/bin/qmlscene -qt=$(/usr/bin/qmlscene -qt=qt5 run
```

/opt/ubuntu-tasks/ubuntu-tasks.qml) run /opt/ubuntu-tasks/ubuntu-tasks.qml

But actually you simply meant: replace that complete line with this line:

```
/usr/bin/qmlscene -qt=qt5 run /opt/ubuntu-tasks/ubuntu-tasks.qml
```

It works for me now.

Regards,
Amedee

**Comment by amedee** [comment]
Launch with:

/usr/bin/qmlscene -qt=qt5 run /opt/ubuntu-tasks/ubuntu-tasks.qml
